"""empty message

Revision ID: 128a4c8ee81c
Revises: 3091ca2e35c8
Create Date: 2021-05-30 13:03:30.463606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128a4c8ee81c'
down_revision = '3091ca2e35c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.Integer(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'state')
    # ### end Alembic commands ###
