"""empty message

Revision ID: 36c91e40c176
Revises: 128a4c8ee81c
Create Date: 2021-05-30 14:22:55.705417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c91e40c176'
down_revision = '128a4c8ee81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    # ### end Alembic commands ###
