"""empty message

Revision ID: cc1000f89181
Revises: 36c91e40c176
Create Date: 2021-05-30 19:18:17.291056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1000f89181'
down_revision = '36c91e40c176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
