"""empty message

Revision ID: e96d6553d89c
Revises: cc1000f89181
Create Date: 2021-05-30 19:19:21.060042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96d6553d89c'
down_revision = 'cc1000f89181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
